// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbrgbkboebsjsvdrzdmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1icmdia2JvZWJzanN2ZHJ6ZG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTg3NjIsImV4cCI6MjA3MjI5NDc2Mn0.azwYbA0v_fYptrO2_-b3Vr6YfYhSGXTRKVhCUg8T6U0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});